"""first revision

Revision ID: 6a713909b2a9
Revises: 
Create Date: 2022-02-10 12:27:34.999962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a713909b2a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_albums_band_id'), 'albums', ['band_id'], unique=False)
    op.create_index(op.f('ix_songs_album_id'), 'songs', ['album_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_album_id'), table_name='songs')
    op.drop_index(op.f('ix_albums_band_id'), table_name='albums')
    # ### end Alembic commands ###
